import { pipeline, AutoTokenizer, AutoModelForCausalLM } from '@xenova/transformers';

// Create a singleton for the feature extraction pipeline
class GPT2Singleton {
  static modelId = 'gpt2';
  static model = null;
  static tokenizer = null;

  static async getInstance(progress_callback = null) {
    if (this.model === null || this.tokenizer === null) {
      // Load the model and tokenizer
      this.model = await AutoModelForCausalLM.from_pretrained(this.modelId, {
        progress_callback,
      });
      this.tokenizer = await AutoTokenizer.from_pretrained(this.modelId, {
        progress_callback,
      });

      // Add padding token if it doesn't exist
      if (!this.tokenizer.padTokenId) {
        this.tokenizer.padTokenId = this.tokenizer.eosTokenId;
      }
    }

    return {
      model: this.model,
      tokenizer: this.tokenizer,
    };
  }
}

/**
 * Initializes the Transformers.js library with GPT-2 model
 */
let transformersInitialized = false;

export const initTensorFlow = async (): Promise<void> => {
  try {
    // This is kept for compatibility with existing code structure
    if (!transformersInitialized) {
      console.log('Transformers.js initialized with GPT-2 model');
      transformersInitialized = true;
    }
  } catch (error) {
    console.error('Failed to initialize Transformers.js:', error);
    throw error;
  }
};

/**
 * Load a pre-trained model for website generation
 * This loads the GPT-2 model using Transformers.js for generating websites
 */
export const loadWebsiteGenerationModel = async () => {
  try {
    console.log('Loading GPT-2 website generation model...');

    // Get the GPT-2 model and tokenizer instance
    const { model, tokenizer } = await GPT2Singleton.getInstance((progress) => {
      console.log(`Model loading progress: ${progress.status || 'loading...'}`);
    });

    console.log('GPT-2 website generation model loaded successfully');
    return { model, tokenizer };
  } catch (error) {
    console.error('Error loading GPT-2 website generation model:', error);
    throw error;
  }
};

/**
 * Generate a website layout based on text description using the GPT-2 model
 * @param description Text description of the desired website
 * @param modelObj Object containing the loaded model and tokenizer
 */
export const generateWebsiteFromDescription = async (description: string, modelObj: any) => {
  try {
    console.log('Generating website from description using GPT-2 model:', description);

    const { model, tokenizer } = modelObj;

    // Create a prompt that guides GPT-2 to generate HTML
    const prompt = `Generate a complete HTML website based on this description: ${description}\n\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>`;

    // Tokenize the input
    const inputs = await tokenizer(prompt, { return_tensors: 'pt', truncation: true, max_length: 512 });

    // Generate the output using GPT-2
    const generated = await model.generate({
      ...inputs, 
      max_new_tokens: 500,  // Limit to reasonable length
      temperature: 0.7,     // Control randomness
      do_sample: true,      // Enable sampling
      pad_token_id: tokenizer.eos_token_id, // Prevent warnings
      repetition_penalty: 1.2, // Reduce repetitive text
    });

    // Decode the generated tokens to text
    const decoded = await tokenizer.batch_decode(generated, { skip_special_tokens: true });

    // Extract the generated HTML portion (everything after the prompt)
    let generatedText = decoded[0].substring(prompt.length);
    
    // Ensure the HTML is properly closed and structured
    generatedText = completeAndSanitizeHTML(generatedText, description);
    
    console.log('Successfully generated website from description using GPT-2');
    return generatedText;
  } catch (error) {
    console.error('Error generating website from description with GPT-2:', error);
    // Fallback to template-based generation if GPT-2 fails
    return generateCompleteWebsiteHTML(description);
  }
};

/**
 * Completes and sanitizes the HTML generated by GPT-2 to ensure it's valid
 * @param htmlFragment The HTML fragment generated by GPT-2
 * @param description Original description to enhance the HTML if needed
 * @returns Complete, valid HTML string
 */
function completeAndSanitizeHTML(htmlFragment: string, description: string): string {
  // Clean up the generated HTML to ensure it's valid
  let cleanHTML = htmlFragment;

  // Remove any extra text that might have been generated after the HTML
  const closingTagIndex = cleanHTML.lastIndexOf('</html>');
  if (closingTagIndex !== -1) {
    cleanHTML = cleanHTML.substring(0, closingTagIndex + 7); // Length of '</html>'
  }

  // If the HTML doesn't contain essential tags, generate a basic template
  if (!cleanHTML.includes('<body') && !cleanHTML.includes('</body>')) {
    return generateCompleteWebsiteHTML(description);
  }

  // Ensure the HTML has proper structure
  if (!cleanHTML.startsWith('<!DOCTYPE html>')) {
    cleanHTML = '<!DOCTYPE html>\n<html lang="pt-BR">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Website Generated by AI</title>\n</head>\n<body>\n' + cleanHTML + '\n</body>\n</html>';
  }

  // Add a basic style to make it look decent if no CSS is present
  if (!cleanHTML.includes('<style>') && !cleanHTML.includes('href=')) {
    const styleTag = '<style>\nbody { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }\n.container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\nh1, h2, h3 { color: #333; }\na { color: #007bff; text-decoration: none; }\na:hover { text-decoration: underline; }\nbutton { background-color: #007bff; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; }\nbutton:hover { background-color: #0056b3; }\n</style>';
    if (cleanHTML.includes('<head>')) {
      cleanHTML = cleanHTML.replace('<head>', '<head>\n' + styleTag);
    } else if (cleanHTML.includes('<body>')) {
      cleanHTML = cleanHTML.replace('<body>', '<body>\n<div class="container">\n' + styleTag);
      if (cleanHTML.includes('</body>')) {
        cleanHTML = cleanHTML.replace('</body>', '\n</div>\n</body>');
      } else {
        cleanHTML += '\n</div>\n</body>';
      }
    }
  }

  return cleanHTML;
}

/**
 * Gera um website HTML completo baseado na descrição
 * @param description Descrição de entrada
 * @returns Saída HTML completa com CSS, JS e bibliotecas
 */
export const generateCompleteWebsiteHTML = (description: string): string => {
  const title = description.split(' ').slice(0, 3).join(' ') || 'AI Generated Site';
  
  // Extract keywords from the description to customize the site
  const keywords = description.toLowerCase().split(' ').filter(word => word.length > 3);
  const primaryColor = keywords.includes('modern') ? '#3B82F6' : 
                      keywords.includes('business') ? '#10B981' : 
                      keywords.includes('creative') ? '#EC4899' : 
                      keywords.includes('tech') ? '#8B5CF6' : '#3B82F6';
  
  return `
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  
  <style>
    :root {
      --primary-color: ${primaryColor};
      --secondary-color: #6366F1;
      --accent-color: #10B981;
    }
    
    body {
      font-family: 'Poppins', sans-serif;
      background-color: #f8fafc;
      color: #334155;
      overflow-x: hidden;
    }
    
    .navbar {
      background-color: rgba(255, 255, 255, 0.95) !important;
      backdrop-filter: blur(10px);
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    
    .hero-section {
      background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
      color: white;
      padding: 100px 0;
      position: relative;
      overflow: hidden;
    }
    
    .hero-section::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: radial-gradient(circle, transparent 20%, #000 150%);
      opacity: 0.1;
    }
    
    .feature-card {
      transition: transform 0.3s ease, box-shadow 0.3s ease;
      height: 100%;
    }
    
    .feature-card:hover {
      transform: translateY(-10px);
      box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    }
    
    .btn-primary {
      background-color: var(--primary-color);
      border-color: var(--primary-color);
    }
    
    .btn-primary:hover {
      background-color: ${adjustColor(primaryColor, -20)};
      border-color: ${adjustColor(primaryColor, -20)};
    }
    
    .section-title {
      position: relative;
      margin-bottom: 2.5rem;
    }
    
    .section-title:after {
      content: '';
      position: absolute;
      bottom: -10px;
      left: 50%;
      transform: translateX(-50%);
      width: 80px;
      height: 4px;
      background: var(--primary-color);
      border-radius: 2px;
    }
    
    .counter {
      font-size: 2.5rem;
      font-weight: 700;
      color: var(--primary-color);
    }
    
    footer {
      background-color: #1e293b;
      color: white;
      padding: 40px 0 20px;
    }
    
    .social-icon {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 40px;
      height: 40px;
      background-color: #334155;
      color: white;
      border-radius: 50%;
      margin-right: 10px;
      transition: all 0.3s ease;
    }
    
    .social-icon:hover {
      background-color: var(--primary-color);
      transform: translateY(-3px);
    }
    
    .animated-bg {
      background-size: 400% 400%;
      animation: gradient 4s ease infinite;
    }
    
    @keyframes gradient {
      0% { background-position: 0% 50%; }
      50% { background-position: 100% 50%; }
      100% { background-position: 0% 50%; }
    }
    
    .aos-init {
      opacity: 1;
      transform: translateY(0);
    }
    
    .aos-animate {
      transition: opacity 0.6s ease, transform 0.6s ease;
    }
  </style>
</head>
<body>
  <!-- Navegação -->
  <nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
      <a class="navbar-brand fw-bold" href="#">
        <i class="fas fa-code me-2"></i>${title}
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" href="#home">Início</a></li>
          <li class="nav-item"><a class="nav-link" href="#about">Sobre</a></li>
          <li class="nav-item"><a class="nav-link" href="#services">Serviços</a></li>
          <li class="nav-item"><a class="nav-link" href="#portfolio">Portfólio</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">Contato</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Seção Herói -->
  <section id="home" class="hero-section text-center position-relative">
    <div class="container position-relative z-index-1">
      <h1 class="display-3 fw-bold mb-4">Bem-vindo ao ${title}</h1>
      <p class="lead mb-5">${description.substring(0, 150)}...</p>
      <div class="d-flex justify-content-center gap-3">
        <a href="#services" class="btn btn-light btn-lg px-4 py-2 fw-bold">Começar</a>
        <a href="#about" class="btn btn-outline-light btn-lg px-4 py-2">Saiba Mais</a>
      </div>
    </div>
  </section>

  <!-- Sobre Nós -->
  <section id="about" class="py-5 my-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 mb-4 mb-lg-0">
          <h2 class="section-title text-center text-lg-start">Sobre Nós</h2>
          <p class="lead">Estamos dedicados a fornecer as melhores soluções para as necessidades do seu negócio.</p>
          <p>${description.substring(0, 200)}...</p>
          <div class="row mt-4">
            <div class="col-md-6">
              <div class="d-flex align-items-center mb-3">
                <div class="me-3 text-primary">
                  <i class="fas fa-check-circle fa-2x"></i>
                </div>
                <h5>Serviço de Qualidade</h5>
              </div>
            </div>
            <div class="col-md-6">
              <div class="d-flex align-items-center mb-3">
                <div class="me-3 text-primary">
                  <i class="fas fa-users fa-2x"></i>
                </div>
                <h5>Equipe Especializada</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="position-relative">
            <img src="https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" alt="Equipe" class="img-fluid rounded shadow">
            <div class="position-absolute top-0 start-0 bg-primary text-white p-3 m-3 rounded">
              <i class="fas fa-briefcase"></i> 5+ Anos de Experiência
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Serviços -->
  <section id="services" class="py-5 bg-light">
    <div class="container">
      <h2 class="section-title text-center mb-5">Nossos Serviços</h2>
      <div class="row g-4">
        <div class="col-md-6 col-lg-4">
          <div class="card feature-card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
              <div class="icon-box bg-primary bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-4">
                <i class="fas fa-laptop-code text-primary fa-2x"></i>
              </div>
              <h4 class="card-title">Desenvolvimento Web</h4>
              <p class="card-text">Sites personalizados construídos com as tecnologias mais recentes para atender às metas do seu negócio.</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="card feature-card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
              <div class="icon-box bg-success bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-4">
                <i class="fas fa-mobile-alt text-success fa-2x"></i>
              </div>
              <h4 class="card-title">Aplicativos Móveis</h4>
              <p class="card-text">Aplicativos móveis nativos e multiplataforma para iOS e Android.</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="card feature-card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
              <div class="icon-box bg-info bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-4">
                <i class="fas fa-chart-line text-info fa-2x"></i>
              </div>
              <h4 class="card-title">Marketing Digital</h4>
              <p class="card-text">Estratégias para aumentar sua presença online e alcançar seu público-alvo.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Portfólio -->
  <section id="portfolio" class="py-5">
    <div class="container">
      <h2 class="section-title text-center mb-5">Nosso Portfólio</h2>
      <div class="row g-4">
        <div class="col-md-6 col-lg-4">
          <div class="card border-0 shadow-sm">
            <img src="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" class="card-img-top" alt="Projeto 1">
            <div class="card-body">
              <h5 class="card-title">Projeto Um</h5>
              <p class="card-text">Uma breve descrição do projeto e suas principais características.</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="card border-0 shadow-sm">
            <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" class="card-img-top" alt="Projeto 2">
            <div class="card-body">
              <h5 class="card-title">Projeto Dois</h5>
              <p class="card-text">Uma breve descrição do projeto e suas principais características.</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="card border-0 shadow-sm">
            <img src="https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" class="card-img-top" alt="Projeto 3">
            <div class="card-body">
              <h5 class="card-title">Projeto Três</h5>
              <p class="card-text">Uma breve descrição do projeto e suas principais características.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Estatísticas -->
  <section class="py-5 bg-primary text-white animated-bg">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-3 col-6 mb-4 mb-md-0">
          <div class="counter">250+</div>
          <p class="mb-0">Projetos Concluídos</p>
        </div>
        <div class="col-md-3 col-6 mb-4 mb-md-0">
          <div class="counter">150+</div>
          <p class="mb-0">Clientes Felizes</p>
        </div>
        <div class="col-md-3 col-6 mb-4 mb-md-0">
          <div class="counter">50+</div>
          <p class="mb-0">Membros da Equipe</p>
        </div>
        <div class="col-md-3 col-6 mb-4 mb-md-0">
          <div class="counter">5+</div>
          <p class="mb-0">Anos de Experiência</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Contato -->
  <section id="contact" class="py-5 bg-light">
    <div class="container">
      <h2 class="section-title text-center mb-5">Entre em Contato</h2>
      <div class="row">
        <div class="col-lg-6 mb-4 mb-lg-0">
          <form>
            <div class="mb-3">
              <label for="name" class="form-label">Nome</label>
              <input type="text" class="form-control" id="name" placeholder="Digite seu nome">
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" placeholder="Digite seu email">
            </div>
            <div class="mb-3">
              <label for="subject" class="form-label">Assunto</label>
              <input type="text" class="form-control" id="subject" placeholder="Digite o assunto">
            </div>
            <div class="mb-3">
              <label for="message" class="form-label">Mensagem</label>
              <textarea class="form-control" id="message" rows="5" placeholder="Digite sua mensagem"></textarea>
            </div>
            <button type="submit" class="btn btn-primary w-100">Enviar Mensagem</button>
          </form>
        </div>
        <div class="col-lg-6">
          <div class="card border-0 shadow-sm h-100">
            <div class="card-body p-5">
              <h4 class="card-title mb-4">Entre em Contato</h4>
              <div class="d-flex mb-3">
                <div class="me-3 text-primary">
                  <i class="fas fa-map-marker-alt fa-2x"></i>
                </div>
                <div>
                  <h6>Localização</h6>
                  <p class="mb-0">Av. Principal, 123, Cidade, País</p>
                </div>
              </div>
              <div class="d-flex mb-3">
                <div class="me-3 text-primary">
                  <i class="fas fa-phone-alt fa-2x"></i>
                </div>
                <div>
                  <h6>Telefone</h6>
                  <p class="mb-0">+55 11 99999-9999</p>
                </div>
              </div>
              <div class="d-flex mb-3">
                <div class="me-3 text-primary">
                  <i class="fas fa-envelope fa-2x"></i>
                </div>
                <div>
                  <h6>Email</h6>
                  <p class="mb-0">contato@exemplo.com</p>
                </div>
              </div>
              <div class="mt-4">
                <h6>Siga-nos</h6>
                <div class="d-flex">
                  <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                  <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
                  <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                  <a href="#" class="social-icon"><i class="fab fa-linkedin-in"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Rodapé -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-4 mb-4 mb-lg-0">
          <h5 class="fw-bold mb-3">${title}</h5>
          <p>${description.substring(0, 100)}...</p>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h5 class="fw-bold mb-3">Links Rápidos</h5>
          <ul class="list-unstyled">
            <li class="mb-2"><a href="#home" class="text-white text-decoration-none">Início</a></li>
            <li class="mb-2"><a href="#about" class="text-white text-decoration-none">Sobre</a></li>
            <li class="mb-2"><a href="#services" class="text-white text-decoration-none">Serviços</a></li>
            <li class="mb-2"><a href="#contact" class="text-white text-decoration-none">Contato</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
          <h5 class="fw-bold mb-3">Serviços</h5>
          <ul class="list-unstyled">
            <li class="mb-2"><a href="#" class="text-white text-decoration-none">Design Web</a></li>
            <li class="mb-2"><a href="#" class="text-white text-decoration-none">Desenvolvimento</a></li>
            <li class="mb-2"><a href="#" class="text-white text-decoration-none">SEO</a></li>
            <li class="mb-2"><a href="#" class="text-white text-decoration-none">Consultoria</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-12">
          <h5 class="fw-bold mb-3">Newsletter</h5>
          <p>Inscreva-se em nossa newsletter para atualizações</p>
          <div class="input-group">
            <input type="email" class="form-control" placeholder="Seu Email">
            <button class="btn btn-primary" type="button">Inscrever</button>
          </div>
        </div>
      </div>
      <hr class="my-4 bg-secondary">
      <div class="text-center">
        <p class="mb-0">&copy; ${new Date().getFullYear()} ${title}. Todos os Direitos Reservados.</p>
      </div>
    </div>
  </footer>

  <!-- Bootstrap JS Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  
  <!-- JavaScript Personalizado -->
  <script>
    // Rolagem suave para links de navegação
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();
        
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
          window.scrollTo({
            top: target.offsetTop - 70,
            behavior: 'smooth'
          });
        }
      });
    });
    
    // Animação ao rolar a página
    const observerOptions = {
      threshold: 0.1,
      rootMargin: '0px 0px -50px 0px'
    };
    
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('aos-animate');
        }
      });
    }, observerOptions);
    
    document.querySelectorAll('[data-aos]').forEach(el => {
      el.classList.add('aos-init');
      observer.observe(el);
    });
    
    // Manipulador de envio de formulário
    const contactForm = document.querySelector('#contact form');
    if (contactForm) {
      contactForm.addEventListener('submit', function(e) {
        e.preventDefault();
        
        // Obter valores do formulário
        const name = document.getElementById('name').value;
        const email = document.getElementById('email').value;
        
        // Mostrar mensagem de sucesso
        alert('Obrigado ' + name + '! Entraremos em contato no email ' + email + ' em breve.');
        
        // Redefinir formulário
        contactForm.reset();
      });
    }
    
    // Animação de contadores
    function animateCounter() {
      const counters = document.querySelectorAll('.counter');
      
      counters.forEach(counter => {
        const updateCount = () => {
          const target = +counter.getAttribute('data-target') || +counter.innerText.replace(/[^0-9]/g, '');
          const count = +counter.innerText.replace(/[^0-9]/g, '');
          
          const increment = target / 200;
          
          if (count < target) {
            counter.innerText = Math.ceil(count + increment);
            setTimeout(updateCount, 10);
          } else {
            counter.innerText = target;
          }
        };
        
        updateCount();
      });
    }
    
    // Acionar animação de contador quando a seção de estatísticas estiver visível
    const statsObserver = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          animateCounter();
          statsObserver.unobserve(entry.target);
        }
      });
    }, { threshold: 0.5 });
    
    const statsSection = document.querySelector('.bg-primary.animated-bg');
    if (statsSection) {
      statsObserver.observe(statsSection);
    }
  </script>
</body>
</html>`;
};

// Função auxiliar para ajustar brilho da cor
function adjustColor(hex: string, percent: number): string {
  // Converte hexadecimal para RGB
  let R = parseInt(hex.substring(1, 3), 16);
  let G = parseInt(hex.substring(3, 5), 16);
  let B = parseInt(hex.substring(5, 7), 16);

  // Ajusta cada componente
  R = Math.min(255, Math.max(0, R + R * percent / 100));
  G = Math.min(255, Math.max(0, G + G * percent / 100));
  B = Math.min(255, Math.max(0, B + B * percent / 100));

  // Converte de volta para hexadecimal
  const RR = Math.round(R).toString(16).padStart(2, '0');
  const GG = Math.round(G).toString(16).padStart(2, '0');
  const BB = Math.round(B).toString(16).padStart(2, '0');

  return '#' + RR + GG + BB;
};